name: eight Workflow
on: 
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: true 
        default: "Hello World"
      selectCustoms:
        description: Select Value
        type: choice
        required: true
        options:
          - Value1
          - Value2
        default: "Value1"
      checkCustom:
        description: Checkbox
        type: boolean
        required: false
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Some text
        run: echo "Some text"
      - name: event Vars
        run: | 
          echo "Title: ${{inputs.titleCustom}}"
          echo "Title: ${{inputs.selectCustoms}}"
          echo "Title: ${{inputs.checkCustom}}"
