name: Fourth Workflow
on: 
  workflow_run: 
    workflows: [Third Workflow]
    types:
      - completed

jobs:
  seccess-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello
        run: echo "Success"
  failier-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Faild"