name: Fourth Workflow
on: 
  workflow_run: 
    workflows: [Third Workflow]
    types:
      - completed

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello world !"
          