name: 14 workflow
on: workflow_dispatch

jobs:
  firs_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
      - name: Cache node mod
        id: cache-step
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: "cache-file"
      - name: Display Cache
        run: echo '${{ toJSON(steps.cache-step.outputs) }}'
      - name: Install node_modules
        run: npm install