name: Sixth Workflow
on: 
  push:
    branches: 
      - main
      - "page/*" # page/about page/blog
      - "page/**" # page/category/lifestyle 
    tags:
      - "v1.*" # v1.1-1.3242
      - "!v1.2.1"
    paths: 
      - "**.html"
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Some text
        run: echo "Some text"
      - name: event Vars
        run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REF