name: Thirteenth Workflow
on: push
jobs:
  # failure() success() cancelled() allways()
  job_success: 
    runs-on: ubuntu-latest
    steps:
      - name: First steps
        run: exit 1
      - name: Runs on cancelled
        if: ${{ cancelled() }}
        run: echo "Runs on cancelled"
      - name: Runs always
        if: ${{ always() }}
        run: echo "Runs on always"
      - name: Runs on success
        if: ${{ success() }}
        run: echo "Runs on success"
      - name: Runs on failure
        if: ${{ failure() }}
        run: echo "Runs on failure"

  second_job:
    runs-on: ubuntu-latest
    needs: job_success
    if: ${{ failure() }}
    steps:
      - run: echo "Job was failid"